version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - store_artifacts:
      #     path: node_modules
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - node_modules

  # test:
  #   docker:
  #     - image: circleci/node:8.10
  #   steps:
  #     - restore_cache:
  #         key: v1-dependencies-
  #     - checkout
  #     # run tests!
  #     - run:
  #         name: Run tests with coverage
  #         command: |
  #           npm install
  #           npm test --coverage

  # Serverless Deployment
  # deploy:
  #   docker:
  #     - image: circleci/node:8.10
  #   steps:
  #     - restore_cache:
  #         key: v1-dependencies-
  #     - checkout
  #     - run:
  #         name: Install Serverless
  #         command: sudo npm i -g serverless
  #     - run:
  #         name: Deploy
  #         # command: sls deploy --stage pre
  #         command: |
  #           if [ "${CIRCLE_BRANCH}" == "dev" ];
  #           then
  #             sls deploy --region us-east-2 --stage dev

  #           elif [ "${CIRCLE_BRANCH}" == "production" ];
  #           then
  #             sls deploy --region us-east-1 --stage prod
  #           fi

  deploy:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Install pyton"
          command: sudo apt-get install -y python3-pip
          # "sudo apt-get -y -qq install awscli"
          # "sudo pip install awscli"
          # "pip install --upgrade awscli"

      - run:
          name: "Install awscli"
          command: pip install awscli
          # "sudo apt-get -y -qq install awscli"
          # "sudo pip install awscli"
          # "pip install --upgrade awscli"

      - run:
          name: "Install awscli"
          command: pip install awscli --upgrade

      - run:
          name: Deploy via AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ];
            then
              npm run deploy-dev
              
            elif [ "${CIRCLE_BRANCH}" == "production" ];
            then
              npm run deploy-prod
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          # - test:
          #     requires:
          #       - build
          filters:
            branches:
              only:
                - dev
                - production
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
                - production
