version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - restore_cache:
          key: v1-dependencies-
      - checkout
      # run tests!
      - run:
          name: Run tests with coverage
          command: |
            npm install
            npm test --coverage

  deploy:
    docker:
      - image: circleci/node:8.10
    steps:
      - restore_cache:
          key: v1-dependencies-
      - checkout
      - run:
          name: Install Serverless
          command: sudo npm i -g serverless
      - run:
          name: Deploy
          # command: sls deploy --stage pre
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              sls deploy --stage dev;
            elif [ "${CIRCLE_BRANCH}"== "production" ]; then   
              sls deploy --stage prod;

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: dev
