version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # persist to reuse in another block ex:test or deploy
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      # run tests!
      - run:
          name: Run tests with coverage
          command: |
            npm run test

      - store_artifacts:
          path: coverage
          prefix: coverage

  # Serverless Deployment
  # deploy:
  #   docker:
  #     - image: circleci/node:8.10
  #   steps:
  #     - restore_cache:
  #         key: v1-dependencies-
  #     - checkout
  #     - run:
  #         name: Install Serverless
  #         command: sudo npm i -g serverless
  #     - run:
  #         name: Deploy
  #         # command: sls deploy --stage pre
  #         command: |
  #           if [ "${CIRCLE_BRANCH}" == "dev" ];
  #           then
  #             sls deploy --region us-east-2 --stage dev

  #           elif [ "${CIRCLE_BRANCH}" == "production" ];
  #           then
  #             sls deploy --region us-east-1 --stage prod
  #           fi

  deploy:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: "Install python"
          command: sudo apt-get install -y python3-pip
      # - run:
      #     name: "Install awscli"
      #     command: sudo pip3 install awscli

      - run:
          name: "Install awscli update"
          command: sudo pip3 install awscli --upgrade

      - run:
          name: Deploy via AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ];
            then
              npm run deploy-dev
              
            elif [ "${CIRCLE_BRANCH}" == "production" ];
            then
              npm run deploy-prod
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
                - production
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - dev
                - production
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - dev
                - production
